## Business Understanding

In today’s fast-paced world, time has become an important factor in people’s daily lives. Food is an essential need, but preparing meals, travelling to restaurants, and waiting for food can be difficult for people with busy schedules, limited mobility, or other personal constraints.

Food delivery platforms such as Zomato have addressed this problem by connecting customers, restaurants, and delivery partners through a technology driven delivery ecosystem. As competition in the food delivery market continues to increase, improving delivery efficiency, customer experience, and operational performance has become increasingly important.

In this project, Zomato's delivery operations data is analyzed to understand the factors that influence delivery performance. The dataset contains information related to delivery time, delivery-person ratings, order type, vehicle condition, weather, traffic density, and city-level operations.

The analysis aims to identify operational challenges and opportunities that can help improve delivery performance and support better business decision-making.

## Business Objectives

The primary objectives of this project are:

1. **Analyze average delivery time** and understand the overall delivery performance.

2. **Identify factors influencing delivery time**, including traffic density, weather conditions, vehicle condition, delivery distance, and other operational variables.

3. **Identify high-order and high-demand locations** and evaluate their delivery performance.

4. **Analyze delivery-person performance** and determine whether ratings and other characteristics are associated with delivery efficiency.

5. **Identify operational bottlenecks and unusual delivery patterns** that may negatively affect customer experience.

6. **Compare delivery performance across cities, order types, traffic conditions, and other relevant segments.**

7. **Provide data-driven recommendations** that can help improve delivery efficiency, operational planning, and customer satisfaction.

## Business Value

This analysis can provide Zomato with a clearer understanding of its delivery operations and the factors affecting delivery performance.

The findings can help the business:

* Improve delivery efficiency in high-demand areas.
* Identify locations and conditions associated with longer delivery times.
* Optimize delivery-partner allocation and operational planning.
* Understand the impact of traffic, weather, and vehicle conditions on delivery performance.
* Identify potential operational bottlenecks and anomalies.
* Improve customer experience by reducing delivery delays.
* Support data-driven decisions regarding resource allocation and operational strategy.

Ultimately, the project aims to transform raw delivery data into actionable business insights that can help improve **operational efficiency, customer satisfaction, and overall business performance**.

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Zomato Dataset.csv")

In [12]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,distance_km,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,10.28,12-02-2022,21.55,22.10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,6.24,13-02-2022,14.55,15.05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,13.79,04-03-2022,17.30,17.40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,2.93,13-02-2022,9.20,9.30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,19.40,14-02-2022,19.50,20.05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45584 entries, 0 to 45583
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       45584 non-null  str
 1   Delivery_person_ID       45584 non-null  str
 2   Delivery_person_Age      43730 non-null  float64
 3   Delivery_person_Ratings  43676 non-null  float64
 4   distance_km              45584 non-null  float64
 5   Order_Date               45584 non-null  str
 6   Time_Orderd              43853 non-null  float64
 7   Time_Order_picked        45584 non-null  float64
 8   Weather_conditions       44968 non-null  str
 9   Road_traffic_density     44983 non-null  str
 10  Vehicle_condition        45584 non-null  int64
 11  Type_of_order            45584 non-null  str
 12  Type_of_vehicle          45584 non-null  str
 13  multiple_deliveries      44591 non-null  float64
 14  Festival                 45356 non-null  str
 15  City                     44384 non-null  str
 16  Time_taken (min)         45584 non-null  int64
dtypes: float64(6), int64(2), str(9)
memory usage: 8.8 MB

 **NULL VALUE EXISTS**

In [14]:
df.describe()

,Delivery_person_Age,Delivery_person_Ratings,distance_km,Time_Orderd,Time_Order_picked,Vehicle_condition,multiple_deliveries,Time_taken (min)
count,43730.000000,43676.000000,45584.000000,43853.000000,45584.000000,45584.000000,44591.000000,45584.000000
mean,29.566911,4.633774,9.735135,16.287218,16.031423,1.023385,0.744635,26.293963
std,5.815064,0.334744,5.608022,6.638570,6.935060,0.839055,0.572510,9.384298
min,15.000000,1.000000,1.470000,0.220000,0.050000,0.000000,0.000000,10.000000
25%,25.000000,4.500000,4.660000,11.500000,11.400000,0.000000,0.000000,19.000000
50%,30.000000,4.700000,9.220000,18.450000,18.450000,1.000000,1.000000,26.000000
75%,35.000000,4.900000,13.680000,21.250000,21.250000,2.000000,1.000000,32.000000
max,50.000000,6.000000,20.970000,23.550000,23.550000,3.000000,3.000000,54.000000

In [15]:
df.nunique()

ID                         45584
Delivery_person_ID          1320
Delivery_person_Age           22
Delivery_person_Ratings       28
distance_km                  267
Order_Date                    44
Time_Orderd                  176
Time_Order_picked            193
Weather_conditions             6
Road_traffic_density           4
Vehicle_condition              4
Type_of_order                  4
Type_of_vehicle                4
multiple_deliveries            4
Festival                       2
City                           3
Time_taken (min)              45
dtype: int64

In [16]:
df.isna().sum()

ID                            0
Delivery_person_ID            0
Delivery_person_Age        1854
Delivery_person_Ratings    1908
distance_km                   0
Order_Date                    0
Time_Orderd                1731
Time_Order_picked             0
Weather_conditions          616
Road_traffic_density        601
Vehicle_condition             0
Type_of_order                 0
Type_of_vehicle               0
multiple_deliveries         993
Festival                    228
City                       1200
Time_taken (min)              0
dtype: int64

**NULL HANDLING REQUIRED**

In [17]:
df.shape

(45584, 17)

**45584 records and 17 columns**

In [18]:
print(df.duplicated().sum())

0

**There are no duplicate rows**